find_path(OPENVINO_INCLUDE_DIR NAMES openvino.hpp PATHS ${CONAN_INCLUDE_DIRS_OPENVINO})

message("CONAN_INCLUDE_DIRS_OPENVINO="${CONAN_INCLUDE_DIRS_OPENVINO})
message("${CONAN_LIBS_OPENVINO}=" ${CONAN_LIBS_OPENVINO})
message("${OPENVINO_INCLUDE_DIR}=" ${OPENVINO_INCLUDE_DIR})
message("${OPENVINO_LIBRARY}=" ${OPENVINO_LIBRARY})

find_library(OPENVINO_LIBRARY NAMES ${CONAN_LIBS_OPENVINO} PATHS ${CONAN_LIB_DIRS_OPENVINO})

set(OPENVINO_FOUND TRUE)
set(OPENVINO_INCLUDE_DIRS ${OPENVINO_INCLUDE_DIR})
set(OPENVINO_LIBRARIES ${OPENVINO_LIBRARY})
mark_as_advanced(OPENVINO_LIBRARY OPENVINO_INCLUDE_DIR)
